name: 构建并推送Docker镜像

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 登录到GitHub容器注册表
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 设置小写的用户名和仓库名称
        id: repo_name
        run: |
          REPO_FULL_NAME=${{ github.repository }}
          REPO_OWNER=$(echo "${REPO_FULL_NAME}" | cut -d'/' -f1 | tr '[:upper:]' '[:lower:]')
          REPO_NAME=$(echo "${REPO_FULL_NAME}" | cut -d'/' -f2 | tr '[:upper:]' '[:lower:]')
          echo "REPO_NAME_LOWER=${REPO_OWNER}/${REPO_NAME}" >> $GITHUB_ENV

      - name: 构建并标记Docker镜像
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: ghcr.io/${{ env.REPO_NAME_LOWER }}:latest
          build-args: |
            SLAVE_SECRET=${{ secrets.SLAVE_SECRET }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: 推送Docker镜像到GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.REPO_NAME_LOWER }}:latest
          build-args: |
            SLAVE_SECRET=${{ secrets.SLAVE_SECRET }}
